version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - type: volume
        source: model_data
        target: /app/models
      - type: volume
        source: app_data
        target: /app/src/data/data

volumes:
  model_data:
  app_data: